In [ ]:
# 딕셔너리를 json 형태로 구성
d = {"name": "혼자 공부하는 데이터 분석"}
print(d['name'])

혼자 공부하는 데이터 분석

In [2]:
import json

In [ ]:
# 딕셔너리 d에 한글이 포함되어 있어, 원래 저장된 문자를 그대로 출력하도록 설정함
d_str = json.dumps(d, ensure_ascii=False)
print(d_str)

{"name": "혼자 공부하는 데이터 분석"}

In [4]:
# d_str이 문자열 객체인지 확인
print(type(d_str))

<class 'str'>

### 웹 기반 API에서 데이터 전송 시 파이썬 객체를 문자열로 바꾸어 전송하는 이유:
> #### 웹 기반 API가 사용하는 HTTP 프로토콜이 텍스트 기반이기 때문에
- 직렬화(serialization): 프로그램 상의 객체를 저장하거나 읽을 수 있는 형태로 변환
- 역직렬화(deserialization): 직렬화된 정보를 다시 프로그램에서 실행 가능한 객체로 변환

In [5]:
d2 = json.loads(d_str)
print(d2['name'])

혼자 공부하는 데이터 분석

In [6]:
print(type(d2))

<class 'dict'>

In [9]:
d3 = json.loads('{"name": "혼자 공부하는 데이터 분석", "author": "박해선", "year": 2022}')
print(d3['name'])
print(d3['author'])
print(d3['year'])

혼자 공부하는 데이터 분석
박해선
2022

In [10]:
d3 = json.loads('{"name": "혼자 공부하는 데이터 분석", "author": ["박해선","홍길동"], "year": 2022}')
print(d3['author'][1])

홍길동

In [11]:
d4_str = """
[
    {"name":"혼자 공부하는 데이터 분석", "author": "박해선", "year": 2022},
    {"name":"혼자 공부하는 머신러닝+딥러닝", "author": "박해선", "year": 2022}
]
"""
d4 = json.loads(d4_str)
print(d4[0]['name'])

혼자 공부하는 데이터 분석

In [12]:
from io import StringIO
import pandas as pd

pd.read_json(StringIO(d4_str))

               name author  year
0    혼자 공부하는 데이터 분석    박해선  2022
1  혼자 공부하는 머신러닝+딥러닝    박해선  2022

In [13]:
pd.DataFrame(d4)

               name author  year
0    혼자 공부하는 데이터 분석    박해선  2022
1  혼자 공부하는 머신러닝+딥러닝    박해선  2022

### XML 데이터 다루기

In [14]:
x_str = """
<book>
    <name>혼자 공부하는 데이터 분석</name>
    <author>박해선</author>
    <year>2022</year>
</book>
"""

In [15]:
import xml.etree.ElementTree as et
book = et.fromstring(x_str)

In [16]:
print(type(book))

<class 'xml.etree.ElementTree.Element'>

In [17]:
print(book.tag)

book

In [18]:
book_childs = list(book)
print(book_childs)

[<Element 'name' at 0x000001F3AD7A21B0>, <Element 'author' at 0x000001F3AD786980>, <Element 'year' at 0x000001F3AD814AE0>]

In [19]:
name, author, year = book_childs
print(name.text)
print(author.text)
print(year.text)

혼자 공부하는 데이터 분석
박해선
2022

#### findtext() 메서드를 사용해야 하는 이유

- XML은 자식 엘리먼트 순서를 항상 일정하게 보장하지 않음
    - findtext() 메서드 사용 시 자식 엘리먼트를 탐색하여 자동으로 텍스트를 반환함

In [20]:
name = book.findtext('name')
author = book.findtext('author')
year = book.findtext('year')
print(name)
print(author)
print(year)

혼자 공부하는 데이터 분석
박해선
2022

In [25]:
x2_str = """
<books>
    <book>
        <name>혼자 공부하는 데이터 분석</name>
        <author>박해선</author>
        <year>2022</year>
    </book>
    <book>
        <name>혼자 공부하는 머신러닝+딥러닝</name>
        <author>박해선</author>
        <year>2020</year>
    </book>
</books>
"""

In [26]:
books = et.fromstring(x2_str)
print(books.tag)

books

In [27]:
for book in books.findall('book'):
    name = book.findtext('name')
    author = book.findtext('author')
    year = book.findtext('year')

    print(name)
    print(author)
    print(year)
    print()

혼자 공부하는 데이터 분석
박해선
2022

혼자 공부하는 머신러닝+딥러닝
박해선
2020

In [28]:
pd.read_xml(x2_str)

C:\Users\user\AppData\Local\Temp\ipykernel_6196\212699965.py:1: FutureWarning: Passing literal xml to 'read_xml' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_xml(x2_str)

               name author  year
0    혼자 공부하는 데이터 분석    박해선  2022
1  혼자 공부하는 머신러닝+딥러닝    박해선  2020